#!/usr/bin/env bash
# script displays content of current directory in a list format Where only the part of the name after the first dash is displayed

for i in *
do
    echo "$i" | cut -d'-' -f2
done
